alias dotfiles='git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias asl='aws sso login'
alias cat='bat'
alias d=docker
alias dbu='docker build'
alias dlg='docker logs'
alias dps='docker ps'
alias dim='docker images'
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcr='docker-compose run'
alias c=clear
alias g=git
alias ga='git add'
alias gc='git commit'
alias gcp='git cherry-pick'
alias gl='git -P log --oneline'
alias gm='git merge'
alias gp='git push'
alias gpr='git pull'
alias gr='git rebase'
alias gs='git status'
alias gsl='git -P shortlog'
alias gst='git stash'
alias gsw='git switch'
alias k=kubectl
alias lzd=lazydocker
alias lzg=lazygit
alias npi='npm install'
alias nps='npm start'
alias npt='npm test'
alias npr='npm run'
alias nprd='npm run dev'
alias nprb='npm run build'
alias npu='npm uninstall'
alias nscripts='cat package.json | jq -r .scripts'
alias ndeps='cat package.json | jq -r .dependencies,.devDependencies'
alias s=sudo
alias q=exit
alias t=tmux
alias tf=terraform
alias weather='curl wttr.in'
alias vi=nvim
