#!/bin/bash

echo "⚡️ Starting Setup"

PROGRAMS=(
    ack
    ag
    awscli
    azure-cli
    blueutil
    cmake
    ctags
    deno
    docker
    doctl
    fzf
    git
    go
    gradle
    httpie
    hub
    hyperkit
    jq
    kubernetes-cli
    liquibase
    macvim
    maven
    minikube
    mongodb-community
    mono
    mutt
    mysql
    node
    nvm
    pandoc
    sbt
    shpotify
    speedtest-cli
    tig
    tldr
    tmux
    tree
    zsh
)

APPS=(
    adoptopenjdk
    dash
    eclipse-jee
    google-chrome
    iterm2
    jetbrains-toolbox
    mongodb-compass-community
    mysqlworkbench
    postman
    slack
    spotify
    springtoolsuite
    visual-studio-code
)

PACKAGES=(
    @angular/cli
    @vue/cli
    caniuse-cmd
    conventional-changelog-cli
    create-react-app
    gatsby-cli
    jest
    lerna
    majestic
    netlify-cli
    next
    node-sass
    nodemon
    parcel
    react-devtools
    release-it
    serve
    ts-node
    typescript
    vsce
    yarn
)

# Install or upgrade Homebrew
which -s brew
if [[ $? != 0 ]] ; then
    echo "🍺 Installing Homebrew"
    /bin/bash -c `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh` > /dev/null
else
    echo "🍻 Upgrading Homebrew"
    brew update > /dev/null
fi

# Install Oh-my-zsh
if ! [[ -d ~/.oh-my-zsh ]]; then
    echo '💥 Installing oh-my-zsh'
    /bin/bash -c `curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh` > /dev/null
fi

# Install Programs
echo "💾 Installing Programs"
brew install "${PROGRAMS[@]}" > /dev/null

# Install Apps
echo "🚀 Installing Apps"
brew cask install --appdir="/Applications" "${APPS[@]}" > /dev/null

# Install NPM Packages
echo "📦 Installing NPM Packages"
npm i -g "${PACKAGES[@]}" > /dev/null

# Clean up
echo "♻️  Performing cleanup"
brew cleanup > /dev/null
rm -f -r /Library/Caches/Homebrew/* > /dev/null

echo "⚡️ Setup complete"

